### ISSUE TITLE
ModuleNotFoundError: No module named 'model.criterion'

### ISSUE THREAD

**Issue by dobedobedo** [LAOS-Y/AgriVision#2]
Hi,
I encountered the below error message when trying to train the dataset
```
(AgriVision) tuy0a@rsws33:~/AgriVision$ nice ./train.sh 0,1 29500 config/agri-resnet101dilated-ibn@a-deeplab-low_feat@3-bce+dice+lovasz-aug-warmup@2000.yaml
CUDA_VISIBLE_DEVICES: 0,1
NUM_GPU: 2
NCCL_SOCKET_IFNAME:
Traceback (most recent call last):
  File "train.py", line 19, in <module>
    from model.dinknet import DinkNet34, DinkNet50, DinkNet101
  File "/home/tuy0a/AgriVision/model/__init__.py", line 1, in <module>
    from .criterion import *
ModuleNotFoundError: No module named 'model.criterion'
Traceback (most recent call last):
  File "train.py", line 19, in <module>
    from model.dinknet import DinkNet34, DinkNet50, DinkNet101
  File "/home/tuy0a/AgriVision/model/__init__.py", line 1, in <module>
    from .criterion import *
ModuleNotFoundError: No module named 'model.criterion'

```
There is no criterion module in the model folder. Could you please advise me how to solve this issue?
PS: I used the existing odgt files rather than generating new ones.

**Comment by kuangsangudu** [comment]
Hi, 
I also get this problem, did you solve this problem?

**Comment by dobedobedo** [comment]
No. I tried to comment out that import but it showed me other error messages.

**Comment by SAOHPRWHG** [comment]
Please try this new version dfcc412, we add the model.criterion in local files.
